"""empty message

Revision ID: cff3d5909c92
Revises: a8422bd2b5e3
Create Date: 2023-09-04 17:30:10.150705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff3d5909c92'
down_revision = 'a8422bd2b5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_question', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('recovery_answer', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['recovery_question'])
        batch_op.create_unique_constraint(None, ['recovery_answer'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('recovery_answer')
        batch_op.drop_column('recovery_question')

    # ### end Alembic commands ###
